site_name: Documentation

docs_dir: Docs

pages:
- ['index.md', 'Introduction']
- ['GettingStarted/Intro.md', 'Getting Started', 'Setting things up']
# - ['APIDocs/WebAPI.md', 'Web API', 'Web API']
# - ['APIDocs/M2MAPI.md', 'M2M API', 'M2M API']
